jenkins:
  systemMessage: "Practice for maven build and jenkins pipeline"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    rolebased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "docker-hub-credentials"
              description: "Docker Hub Credentials"
              username: "${docker-hub-username}"
              password: "${docker-hub-password}"


tool:
  maven:
    installations:
      - name: "Maven 3.8.5"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.5" 
  jdk:
    installations:
      - name: "JDK 17"
        home: "/opt/java/openjdk" 
jobs:
  - file: /var/jenkins_home/init.groovy.d/job_dsl.groovy
